# Autogenerated wrapper script for Channelflow_jll for x86_64-linux-gnu-cxx11
export continuesoln

using FFTW_jll
using HDF5_jll
using Eigen_jll
using NetCDF_jll
JLLWrappers.@generate_wrapper_header("Channelflow")
JLLWrappers.@declare_executable_product(continuesoln)
function __init__()
    JLLWrappers.@generate_init_header(FFTW_jll, HDF5_jll, Eigen_jll, NetCDF_jll)
    JLLWrappers.@init_executable_product(
        continuesoln,
        "bin/continuesoln",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
